// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpVFzH9ZO6PXoZd53WqHATVKrKTqlbyXE',
    appId: '1:753267951652:web:e74c7d83fdc81e1e63f0b1',
    messagingSenderId: '753267951652',
    projectId: 'chatapp-21708',
    authDomain: 'chatapp-21708.firebaseapp.com',
    storageBucket: 'chatapp-21708.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM1DAd_5XGqQSIZl59QvUpbUKjAYpcueo',
    appId: '1:753267951652:android:495e31c7582db51163f0b1',
    messagingSenderId: '753267951652',
    projectId: 'chatapp-21708',
    storageBucket: 'chatapp-21708.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjHVGK6osREYI66bwbQ0U0h9t_C47o9H0',
    appId: '1:753267951652:ios:00b6b0fe1961d27f63f0b1',
    messagingSenderId: '753267951652',
    projectId: 'chatapp-21708',
    storageBucket: 'chatapp-21708.appspot.com',
    iosClientId: '753267951652-31i9va4uu8bjlksbhknu1mpr5hh9r8ko.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjHVGK6osREYI66bwbQ0U0h9t_C47o9H0',
    appId: '1:753267951652:ios:85925a5dece7f82363f0b1',
    messagingSenderId: '753267951652',
    projectId: 'chatapp-21708',
    storageBucket: 'chatapp-21708.appspot.com',
    iosClientId: '753267951652-cv6amhb0n8qe40nh4m1ktbsqejirbhbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppWithFirebase.RunnerTests',
  );
}
